CREATE SCHEMA IF NOT EXISTS`login`;
USE `login`;

CREATE TABLE dados (
    ID INT AUTO_INCREMENT NOT NULL,
    `LOGIN` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);